coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "src/**/*.d.ts"
  - "src/**/*.stories.*"
  - "src/app/layout.tsx"
  - "src/app/globals.css"
