-- Migration 015: Weekly Digests
-- Story 11.7: Weekly Financial Digest (ADR-019)
-- One row per user per week, generated by /api/cron/weekly-digest on Monday 08:00 UTC

CREATE TABLE IF NOT EXISTS public.weekly_digests (
  id                     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start             DATE NOT NULL,
  week_end               DATE NOT NULL,
  total_spending         DECIMAL(12, 2) NOT NULL CHECK (total_spending >= 0),
  previous_week_spending DECIMAL(12, 2) NOT NULL CHECK (previous_week_spending >= 0),
  spending_change_pct    DECIMAL(8, 2) NOT NULL,  -- negative = decrease, positive = increase
  top_categories         JSONB NOT NULL DEFAULT '[]',     -- Array<{category_id, name, color, total}>
  actionable_highlight   TEXT NOT NULL DEFAULT '',
  currency               VARCHAR(3) NOT NULL DEFAULT 'EUR',
  generated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_start)
);

COMMENT ON TABLE  public.weekly_digests IS 'One row per user per week. Generated by /api/cron/weekly-digest (ADR-019).';
COMMENT ON COLUMN public.weekly_digests.week_start IS 'ISO Monday of the summarised week (inclusive)';
COMMENT ON COLUMN public.weekly_digests.week_end   IS 'ISO Sunday of the summarised week (inclusive)';
COMMENT ON COLUMN public.weekly_digests.top_categories IS 'JSON array [{category_id, name, color, total}] top 3 by spending';
COMMENT ON COLUMN public.weekly_digests.spending_change_pct IS 'Percent change vs previous week; negative = lower spending';

ALTER TABLE public.weekly_digests ENABLE ROW LEVEL SECURITY;

-- Users can only read their own digests; cron uses service-role which bypasses RLS
CREATE POLICY "Users can read own weekly digests"
  ON public.weekly_digests FOR SELECT
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_digests_user_id
  ON public.weekly_digests (user_id, week_start DESC);
